CREATE TABLE [dim].[RT_BusDatabase] (
    [VehicleKey]             INT            IDENTITY (1, 1) NOT NULL,
    [InternalNumber]         INT            NOT NULL,
    [RegistrationNumber]     NVARCHAR (50)  NULL,
    [ChassisNumber]          NVARCHAR (50)  NULL,
    [ChassisSupplier]        NVARCHAR (50)  NULL,
    [BodySupplier]           NVARCHAR (50)  NULL,
    [BusModel]               NVARCHAR (50)  NULL,
    [BusType]                NVARCHAR (50)  NULL,
    [FloorType]              NVARCHAR (50)  NULL,
    [Contractor]             NVARCHAR (50)  NULL,
    [SubContractor]          NVARCHAR (50)  NULL,
    [SpecialEquipment]       NVARCHAR (255) NULL,
    [Aircon]                 BIT            NULL,
    [AirConText]             VARCHAR (5)    NULL,
    [DesignPainting]         NVARCHAR (50)  NULL,
    [NumberOfSeats]          INT            NULL,
    [NumberOfFoldingSeats]   INT            NULL,
    [NumberOfPitches]        INT            NULL,
    [ApprovedTotalCapacity]  NVARCHAR (50)  NULL,
    [DoorConfiguration]      NVARCHAR (50)  NULL,
    [NumberOfBabyCarriages]  NVARCHAR (50)  NULL,
    [Length]                 FLOAT (53)     NULL,
    [Width]                  FLOAT (53)     NULL,
    [Height]                 FLOAT (53)     NULL,
    [ShaftDistance]          FLOAT (53)     NULL,
    [OwnWeight]              FLOAT (53)     NULL,
    [TotalWeight]            FLOAT (53)     NULL,
    [EmissionNorm]           NVARCHAR (50)  NULL,
    [Fuel]                   NVARCHAR (50)  NULL,
    [EmissionsEquipment]     NVARCHAR (50)  NULL,
    [NOx]                    NVARCHAR (50)  NULL,
    [Hc]                     NVARCHAR (50)  NULL,
    [Co]                     NVARCHAR (50)  NULL,
    [Pm]                     NVARCHAR (50)  NULL,
    [DieselConsumptionSORT1] FLOAT (53)     NULL,
    [DieselConsumptionSORT2] FLOAT (53)     NULL,
    [DieselConsumptionSORT3] FLOAT (53)     NULL,
    [CO2PerKMSORT1]          NVARCHAR (50)  NULL,
    [CO2PerKMSORT2]          NVARCHAR (50)  NULL,
    [CO2PerKMSORT3]          NVARCHAR (50)  NULL,
    [Efficiency]             NVARCHAR (50)  NULL,
    [NoiseInside2008]        FLOAT (53)     NULL,
    [NoiseOutside2008]       FLOAT (53)     NULL,
    [NoiseInside2017]        FLOAT (53)     NULL,
    [NoiseOutside2017]       FLOAT (53)     NULL,
    [Garage]                 NVARCHAR (50)  NULL,
    [Procurement]            NVARCHAR (50)  NULL,
    [ContractUnit]           NVARCHAR (50)  NULL,
    [Infotainment]           BIT            NULL,
    [InfotainmentText]       VARCHAR (5)    NULL,
    [Lines]                  NVARCHAR (255) NULL,
    [ReserveBus]             BIT            NULL,
    [FirstRegistrationDate]  DATE           NULL,
    [FirstCommissioningDate] DATE           NULL,
    [InUse]                  NVARCHAR (50)  NULL,
    [Obs]                    NVARCHAR (255) NULL,
    [InfotainmentSupplier]   NVARCHAR (50)  NULL,
    [OperatingTermination]   NVARCHAR (50)  NULL,
    [Flowtype]               NVARCHAR (50)  NULL,
    [CountBus]               BIT            NULL,
    [NewRealTime]            BIT            NULL,
    [SupplierRealTime]       NVARCHAR (50)  NULL,
    [LastModified]           DATETIME2 (7)  NULL,
    [GarageRef]              NVARCHAR (50)  NULL,
    [GarageAddress]          NVARCHAR (50)  NULL,
    [ContractorRef]          NVARCHAR (50)  NULL,
    [Electric]               BIT            NULL,
    [ElectricText]           VARCHAR (5)    NULL,
    [ValidFromDate]          DATE           NULL,
    [ValidToDate]            DATE           NULL,
    [IsCurrent]              BIT            NULL,
    [Id]                     NVARCHAR (50)  NOT NULL,
    [Inserted]               DATETIME2 (7)  NULL,
    [Updated]                DATETIME2 (7)  NULL,
    CONSTRAINT [PK_RT_BusDatabase] PRIMARY KEY CLUSTERED ([VehicleKey] ASC)
);


GO

CREATE UNIQUE NONCLUSTERED INDEX [UQ_RT_BusDatabase_Merge]
    ON [dim].[RT_BusDatabase]([InternalNumber] ASC, [ValidFromDate] ASC);


GO

