CREATE TABLE [stg].[GIS_StopPoint_Equipment] (
    [Longitude]              FLOAT (53)       NULL,
    [Latitude]               FLOAT (53)       NULL,
    [GlobalID]               UNIQUEIDENTIFIER NULL,
    [Number]                 INT              NULL,
    [Name]                   NVARCHAR (255)   NULL,
    [Buslines]               NVARCHAR (255)   NULL,
    [ChangedDate_]           BIGINT           NULL,
    [ChangedDate]            DATETIME2 (0)    NULL,
    [StopType]               SMALLINT         NULL,
    [BusstopLength]          SMALLINT         NULL,
    [BicyclePath]            SMALLINT         NULL,
    [Refuge]                 SMALLINT         NULL,
    [StopSurface]            SMALLINT         NULL,
    [GuideAttentionFields]   SMALLINT         NULL,
    [StandType]              SMALLINT         NULL,
    [StandColour]            SMALLINT         NULL,
    [Year]                   SMALLINT         NULL,
    [HolderType]             SMALLINT         NULL,
    [N_spaces]               SMALLINT         NULL,
    [CountdownType]          SMALLINT         NULL,
    [CountdownModel]         NVARCHAR (255)   NULL,
    [CountdownID]            INT              NULL,
    [CdmsDataUpdated_]       BIGINT           NULL,
    [CdmsDataUpdated]        DATETIME2 (0)    NULL,
    [BeaconType]             NVARCHAR (255)   NULL,
    [BeaconID]               SMALLINT         NULL,
    [OtherDigInfo]           SMALLINT         NULL,
    [DigInfoCphMun]          SMALLINT         NULL,
    [Windbreaker]            SMALLINT         NULL,
    [ComFinancedWindbreaker] SMALLINT         NULL,
    [OtherShelter]           SMALLINT         NULL,
    [Bench]                  SMALLINT         NULL,
    [TrashCan]               SMALLINT         NULL,
    [CycleParking]           SMALLINT         NULL,
    [MapInWindbreaker]       SMALLINT         NULL,
    [LinesPerStop]           SMALLINT         NULL,
    [StrategicNet]           SMALLINT         NULL,
    [ProductType]            NVARCHAR (255)   NULL,
    [Municipality]           SMALLINT         NULL,
    [Region]                 SMALLINT         NULL,
    [CreatedDate_]           BIGINT           NULL,
    [CreatedDate]            DATETIME2 (0)    NULL,
    [OBJECTID]               BIGINT           NULL
);


GO

