CREATE TABLE [stg].[IT_FinOps_AzureCost] (
    [InvoiceSectionName]     NVARCHAR (255)   NULL,
    [AccountName]            NVARCHAR (255)   NULL,
    [AccountOwnerId]         NVARCHAR (255)   NULL,
    [SubscriptionId]         NVARCHAR (255)   NULL,
    [SubscriptionName]       NVARCHAR (255)   NULL,
    [ResourceGroup]          NVARCHAR (255)   NULL,
    [ResourceLocation]       NVARCHAR (255)   NULL,
    [Date]                   DATE             NULL,
    [ProductName]            NVARCHAR (255)   NULL,
    [MeterCategory]          NVARCHAR (255)   NULL,
    [MeterSubCategory]       NVARCHAR (255)   NULL,
    [MeterId]                NVARCHAR (255)   NULL,
    [MeterName]              NVARCHAR (255)   NULL,
    [MeterRegion]            NVARCHAR (255)   NULL,
    [UnitOfMeasure]          NVARCHAR (255)   NULL,
    [Quantity]               DECIMAL (36, 18) NULL,
    [EffectivePrice]         DECIMAL (36, 18) NULL,
    [CostInBillingCurrency]  DECIMAL (36, 18) NULL,
    [CostCenter]             NVARCHAR (255)   NULL,
    [ConsumedService]        NVARCHAR (255)   NULL,
    [ResourceId]             NVARCHAR (1024)  NULL,
    [Tags]                   NVARCHAR (MAX)   NULL,
    [OfferId]                NVARCHAR (255)   NULL,
    [AdditionalInfo]         NVARCHAR (MAX)   NULL,
    [ServiceInfo1]           NVARCHAR (1024)  NULL,
    [ServiceInfo2]           NVARCHAR (1024)  NULL,
    [ResourceName]           NVARCHAR (255)   NULL,
    [ReservationId]          NVARCHAR (255)   NULL,
    [ReservationName]        NVARCHAR (255)   NULL,
    [UnitPrice]              DECIMAL (36, 18) NULL,
    [ProductOrderId]         NVARCHAR (255)   NULL,
    [ProductOrderName]       NVARCHAR (255)   NULL,
    [Term]                   NVARCHAR (255)   NULL,
    [PublisherType]          NVARCHAR (255)   NULL,
    [PublisherName]          NVARCHAR (255)   NULL,
    [ChargeType]             NVARCHAR (255)   NULL,
    [Frequency]              NVARCHAR (255)   NULL,
    [PricingModel]           NVARCHAR (255)   NULL,
    [AvailabilityZone]       NVARCHAR (255)   NULL,
    [BillingAccountId]       NVARCHAR (255)   NULL,
    [BillingAccountName]     NVARCHAR (255)   NULL,
    [BillingCurrencyCode]    NVARCHAR (255)   NULL,
    [BillingPeriodStartDate] DATE             NULL,
    [BillingPeriodEndDate]   DATE             NULL,
    [BillingProfileId]       NVARCHAR (255)   NULL,
    [BillingProfileName]     NVARCHAR (255)   NULL,
    [InvoiceSectionId]       NVARCHAR (255)   NULL,
    [IsAzureCreditEligible]  NVARCHAR (255)   NULL,
    [PartNumber]             NVARCHAR (255)   NULL,
    [PayGPrice]              NVARCHAR (255)   NULL,
    [PlanName]               NVARCHAR (255)   NULL,
    [ServiceFamily]          NVARCHAR (255)   NULL,
    [CostAllocationRuleName] NVARCHAR (255)   NULL,
    [benefitId]              NVARCHAR (255)   NULL,
    [benefitName]            NVARCHAR (255)   NULL,
    [LastModifiedUtc]        DATETIME2 (3)    NULL,
    [YearMonth]              INT              NULL
);


GO

