CREATE TABLE [stg].[QA_DigitalSurvey_QuestionaryUnpivotX] (
    [survey]   INT             NULL,
    [responde] INT             NULL,
    [organiza] INT             NULL,
    [stat_1]   INT             NULL,
    [stat_2]   INT             NULL,
    [stat_3]   INT             NULL,
    [stat_4]   INT             NULL,
    [stat_5]   INT             NULL,
    [stat_6]   INT             NULL,
    [stat_7]   INT             NULL,
    [stat_8]   INT             NULL,
    [stat_9]   INT             NULL,
    [stat_10]  INT             NULL,
    [stat_11]  INT             NULL,
    [stat_12]  INT             NULL,
    [stat_13]  INT             NULL,
    [stat_14]  INT             NULL,
    [stat_15]  INT             NULL,
    [stat_16]  INT             NULL,
    [stat_17]  INT             NULL,
    [stat_18]  INT             NULL,
    [stat_19]  INT             NULL,
    [stat_20]  INT             NULL,
    [stat_21]  INT             NULL,
    [stat_22]  INT             NULL,
    [stat_23]  INT             NULL,
    [stat_24]  INT             NULL,
    [stat_25]  INT             NULL,
    [created]  DATETIME        NULL,
    [modified] DATETIME        NULL,
    [closetim] DATETIME        NULL,
    [starttim] DATETIME        NULL,
    [difftime] FLOAT (53)      NULL,
    [response] INT             NULL,
    [numberof] INT             NULL,
    [importgr] NVARCHAR (255)  NULL,
    [distribu] NVARCHAR (255)  NULL,
    [email]    NVARCHAR (255)  NULL,
    [s_1]      INT             NULL,
    [s_2]      INT             NULL,
    [s_3]      NVARCHAR (4000) NULL,
    [s_4]      INT             NULL,
    [s_5]      NVARCHAR (4000) NULL,
    [s_6]      INT             NULL,
    [s_7]      NVARCHAR (4000) NULL,
    [s_8]      INT             NULL,
    [s_9_1]    INT             NULL,
    [s_9_2]    INT             NULL,
    [s_9_3]    INT             NULL,
    [s_9_4]    INT             NULL,
    [s_10]     INT             NULL,
    [s_11]     NVARCHAR (255)  NULL,
    [s_12]     INT             NULL,
    [s_20]     NVARCHAR (50)   NULL,
    [b_1]      INT             NULL,
    [c_1]      INT             NULL,
    [statc_1]  INT             NULL,
    [statc_2]  INT             NULL,
    [statc_3]  INT             NULL,
    [statc_4]  INT             NULL,
    [statc_5]  INT             NULL,
    [statc_6]  INT             NULL,
    [statc_7]  INT             NULL,
    [statc_8]  INT             NULL,
    [statc_9]  INT             NULL,
    [statd_1]  INT             NULL,
    [statd_2]  INT             NULL,
    [statd_3]  INT             NULL,
    [statd_4]  INT             NULL,
    [statd_5]  INT             NULL,
    [stato_1]  INT             NULL,
    [stato_2]  INT             NULL,
    [stato_3]  INT             NULL,
    [stato_4]  INT             NULL,
    [stato_5]  INT             NULL,
    [stats_1]  INT             NULL,
    [stats_2]  INT             NULL,
    [stats_3]  INT             NULL,
    [stats_4]  INT             NULL,
    [stats_5]  INT             NULL,
    [stats_6]  INT             NULL,
    [s_9_5]    INT             NULL,
    [s_13]     NVARCHAR (4000) NULL,
    [s_14]     NVARCHAR (4000) NULL,
    [s_22]     NVARCHAR (4000) NULL,
    [digitald] INT             NULL,
    [digit_1]  NVARCHAR (255)  NULL
);


GO

CREATE UNIQUE NONCLUSTERED INDEX [UQ_QA_DigitalSurvey_Data_Merge]
    ON [stg].[QA_DigitalSurvey_QuestionaryUnpivotX]([survey] ASC, [responde] ASC)
    INCLUDE([b_1], [c_1], [closetim], [created], [stats_4], [stats_5], [stats_6], [stato_3], [stato_4], [stato_5], [stats_1], [stats_2], [stats_3], [statd_2], [statd_3], [statd_4], [statd_5], [stato_1], [stato_2], [statc_5], [statc_6], [statc_7], [statc_8], [statc_9], [statd_1], [stat_8], [stat_9], [statc_1], [statc_2], [statc_3], [statc_4], [stat_25], [stat_3], [stat_4], [stat_5], [stat_6], [stat_7], [stat_2], [stat_20], [stat_21], [stat_22], [stat_23], [stat_24], [stat_14], [stat_15], [stat_16], [stat_17], [stat_18], [stat_19], [starttim], [stat_1], [stat_10], [stat_11], [stat_12], [stat_13], [s_8], [s_9_1], [s_9_2], [s_9_3], [s_9_4], [s_9_5], [s_22], [s_3], [s_4], [s_5], [s_6], [s_7], [s_11], [s_12], [s_13], [s_14], [s_2], [s_20], [modified], [numberof], [organiza], [response], [s_1], [s_10], [difftime], [digit_1], [digitald], [distribu], [email], [importgr]);


GO

