CREATE TABLE [stg].[RK_Rejsebillet_SingleTicket] (
    [TicketEncryptedID]     NVARCHAR (100)  NULL,
    [AccountingEncryptedID] NVARCHAR (100)  NULL,
    [OrderEncryptedID]      NVARCHAR (100)  NULL,
    [TicketType]            NVARCHAR (100)  NULL,
    [ProductCD]             INT             NULL,
    [Productname]           NVARCHAR (100)  NULL,
    [PassengerType]         NVARCHAR (100)  NULL,
    [SalesDT]               DATE            NULL,
    [SalesDT_]              NVARCHAR (10)   NULL,
    [IssueDTTM]             DATETIME        NULL,
    [IssueDTTM_]            NVARCHAR (50)   NULL,
    [Udførende]             NVARCHAR (100)  NULL,
    [AntalRejser]           INT             NULL,
    [Refusion]              BIT             NULL,
    [Refusion_]             INT             NULL,
    [RejsePris]             NUMERIC (11, 2) NULL,
    [Rejsepris_]            INT             NULL,
    [PaymentRecivedFLG]     NVARCHAR (100)  NULL,
    [PaymentChangeDTTM]     DATETIME        NULL,
    [PaymentChangeDTTM_]    NVARCHAR (50)   NULL,
    [OrigStartZoneID]       NVARCHAR (100)  NULL,
    [ZoneStartID]           INT             NULL,
    [ZoneStartID_]          NVARCHAR (50)   NULL,
    [ZoneEndID]             INT             NULL,
    [ZoneEndID_]            NVARCHAR (50)   NULL,
    [ZonesPayed]            INT             NULL,
    [ZonesValid]            INT             NULL,
    [StopPointStartID]      NUMERIC (9)     NULL,
    [StopPointStartIDtxt]   NVARCHAR (100)  NULL,
    [StopPointEndID]        NUMERIC (9)     NULL,
    [StopPointEndIDtxt]     NVARCHAR (100)  NULL,
    [FareSetID]             INT             NULL,
    [FareSetIDTXT]          NVARCHAR (100)  NULL,
    [landsdel]              NVARCHAR (100)  NULL,
    [TakstOmraade]          NVARCHAR (100)  NULL,
    [ValidityStartDTTM]     DATETIME        NULL,
    [ValidityStartDTTM_]    NVARCHAR (50)   NULL,
    [ValidityEndDTTM]       DATETIME        NULL,
    [ValidityEndDTTM_]      NVARCHAR (50)   NULL,
    [Delingsregel]          NVARCHAR (100)  NULL,
    [RBindt_Arriva]         NUMERIC (13, 4) NULL,
    [RBindt_Arriva_]        INT             NULL,
    [RBindt_BAT]            NUMERIC (13, 4) NULL,
    [RBindt_BAT_]           INT             NULL,
    [RBindt_DSB]            NUMERIC (13, 4) NULL,
    [RBindt_DSB_]           INT             NULL,
    [RBindt_EjFordelt]      NUMERIC (13, 4) NULL,
    [RBindt_EjFordelt_]     INT             NULL,
    [RBindt_Fynbus]         NUMERIC (13, 4) NULL,
    [RBindt_Fynbus_]        INT             NULL,
    [RBindt_Metro]          NUMERIC (13, 4) NULL,
    [RBindt_Metro_]         INT             NULL,
    [RBindt_Midttrafik]     NUMERIC (13, 4) NULL,
    [RBindt_Midttrafik_]    INT             NULL,
    [RBindt_MoviaH]         NUMERIC (13, 4) NULL,
    [RBindt_MoviaH_]        INT             NULL,
    [RBindt_MoviaS]         NUMERIC (13, 4) NULL,
    [RBindt_MoviaS_]        INT             NULL,
    [RBindt_MoviaV]         NUMERIC (13, 4) NULL,
    [RBindt_MoviaV_]        INT             NULL,
    [RBindt_NT]             NUMERIC (13, 4) NULL,
    [RBindt_NT_]            INT             NULL,
    [RBindt_Sydtrafik]      NUMERIC (13, 4) NULL,
    [RBindt_Sydtrafik_]     INT             NULL,
    [Status]                INT             NULL,
    [RunDTTM]               DATETIME        NULL,
    [RunDTTM_]              NVARCHAR (50)   NULL,
    [SourceSystemCode]      NVARCHAR (15)   NULL,
    [MediaTypeCode]         NVARCHAR (5)    NULL,
    [SalesChannelCode]      NVARCHAR (15)   NULL,
    [ZoneList]              NVARCHAR (MAX)  NULL
);


GO

