CREATE TABLE [stg].[RK_Transaction_Operational_Pb] (
    [TransactionID]                        BIGINT         NOT NULL,
    [FileName]                             NCHAR (12)     NULL,
    [BusinessDay]                          DATE           NULL,
    [BusinessHour]                         TINYINT        NULL,
    [BusinessQuarterHour]                  TINYINT        NULL,
    [EquipmentID]                          INT            NULL,
    [EquipmentType]                        TINYINT        NULL,
    [SiteID]                               INT            NULL,
    [MessageReceptionDate]                 DATETIME2 (0)  NULL,
    [Period]                               INT            NULL,
    [IsReintegratedTransaction]            TINYINT        NULL,
    [ReintegratedDateTime]                 DATETIME2 (0)  NULL,
    [MsgReportDate]                        DATETIME2 (0)  NULL,
    [MediaSerialNumberID]                  BIGINT         NULL,
    [ApplicationTransactionSequenceNumber] INT            NULL,
    [MsgSequenceNumber]                    BIGINT         NULL,
    [DeviceId]                             INT            NULL,
    [TransactionType]                      TINYINT        NULL,
    [TransactionBusinessDate]              DATE           NULL,
    [TransactionStatus]                    TINYINT        NULL,
    [TransactionMediaLastDeviceID]         INT            NULL,
    [ServiceProviderID]                    SMALLINT       NULL,
    [ContractorID]                         SMALLINT       NULL,
    [FareAuthorityID]                      SMALLINT       NULL,
    [StationID]                            INT            NULL,
    [StopPointID]                          BIGINT         NULL,
    [ModalType]                            TINYINT        NULL,
    [ServiceJourneyType]                   INT            NULL,
    [StaffID]                              INT            NULL,
    [StaffType]                            TINYINT        NULL,
    [ShiftNumber]                          BIGINT         NULL,
    [MediaCountryCode]                     SMALLINT       NULL,
    [MediaIssuerID]                        SMALLINT       NULL,
    [MediaRetailerID]                      SMALLINT       NULL,
    [MediaType]                            TINYINT        NULL,
    [MediaValidityDate]                    DATE           NULL,
    [MediaVersion]                         TINYINT        NULL,
    [MediaSecurityLevel]                   TINYINT        NULL,
    [MediaTest]                            BIT            NULL,
    [CardEngravedID]                       BIGINT         NULL,
    [ApplicationStatus]                    TINYINT        NULL,
    [ActionListStatus]                     TINYINT        NULL,
    [ActionListID]                         BIGINT         NULL,
    [ActionListFailureCode]                TINYINT        NULL,
    [CSCCurrencyUnit]                      INT            NULL,
    [SystemCurrencyUnit]                   INT            NULL,
    [EODVersionID]                         SMALLINT       NULL,
    [EODVersionComponent1]                 SMALLINT       NULL,
    [EODVersionComponent2]                 SMALLINT       NULL,
    [EODVersionComponent3]                 SMALLINT       NULL,
    [EODVersionComponent4]                 SMALLINT       NULL,
    [EODVersionComponent5]                 SMALLINT       NULL,
    [EODVersionComponent6]                 SMALLINT       NULL,
    [EODVersionComponent7]                 SMALLINT       NULL,
    [EODVersionComponent8]                 SMALLINT       NULL,
    [EODVersionComponent9]                 SMALLINT       NULL,
    [TrackingOperationType]                TINYINT        NULL,
    [TrackingOperationNumber]              INT            NULL,
    [VehicleID]                            INT            NULL,
    [RouteID]                              INT            NULL,
    [TripID]                               BIGINT         NULL,
    [TripTimeDeparture]                    NVARCHAR (255) NULL,
    [LinePublicNumber]                     NVARCHAR (6)   NULL,
    [TripType]                             TINYINT        NULL,
    [StockOperationSequenceNumber]         BIGINT         NULL,
    [CalculatedMediaQuantity]              SMALLINT       NULL,
    [ReasonCodeStockManagement]            TINYINT        NULL,
    [StockAction]                          TINYINT        NULL,
    [OperationAction]                      TINYINT        NULL,
    [OperationType]                        TINYINT        NULL,
    [FilePath]                             NVARCHAR (255) NULL,
    [FileId]                               INT            NULL
);


GO

