CREATE TABLE [stg].[RT_BusDatabase_Bus] (
    [Id]                    UNIQUEIDENTIFIER NOT NULL,
    [InternalNumber]        INT              NULL,
    [RegistrationNumber]    NVARCHAR (MAX)   NULL,
    [ChassisNumber]         NVARCHAR (MAX)   NULL,
    [BusModel]              NVARCHAR (MAX)   NULL,
    [BusType]               NVARCHAR (MAX)   NULL,
    [FloorType]             NVARCHAR (MAX)   NULL,
    [Contractor]            NVARCHAR (MAX)   NULL,
    [SubContractor]         NVARCHAR (MAX)   NULL,
    [SpecialEquipment]      NVARCHAR (MAX)   NULL,
    [Aircon]                BIT              NULL,
    [DesignPainting]        NVARCHAR (MAX)   NULL,
    [NumberOfSeats]         INT              NULL,
    [NumberOfFoldingSeats]  INT              NULL,
    [NumberOfPitches]       INT              NULL,
    [ApprovedTotalCapacity] NVARCHAR (MAX)   NULL,
    [DoorConfiguration]     NVARCHAR (MAX)   NULL,
    [NumberOfBabyCarriages] NVARCHAR (MAX)   NULL,
    [Length]                FLOAT (53)       NULL,
    [Width]                 FLOAT (53)       NULL,
    [Height]                FLOAT (53)       NULL,
    [ShaftDistance]         FLOAT (53)       NULL,
    [OwnWeight]             FLOAT (53)       NULL,
    [TotalWeight]           FLOAT (53)       NULL,
    [EmissionNorm]          NVARCHAR (MAX)   NULL,
    [Fuel]                  NVARCHAR (MAX)   NULL,
    [EmissionsEquipment]    NVARCHAR (MAX)   NULL,
    [NoiseOutside2008]      INT              NULL,
    [NoiseInside2008]       INT              NULL,
    [OBS]                   NVARCHAR (MAX)   NULL,
    [NoiseInside2017]       INT              NULL,
    [Garage]                NVARCHAR (MAX)   NULL,
    [Procurement]           NVARCHAR (MAX)   NULL,
    [ContractUnit]          NVARCHAR (MAX)   NULL,
    [Infotainment]          BIT              NULL,
    [Lines]                 NVARCHAR (MAX)   NULL,
    [ReserveBus]            BIT              NULL,
    [FirstRegistrationDate] DATETIME2 (7)    NULL,
    [NoiseOutside2017]      INT              NULL,
    [InUse]                 NVARCHAR (MAX)   NULL,
    [LastModified]          DATETIME2 (7)    NOT NULL,
    [CountBus]              BIT              NULL,
    [Flowtype]              NVARCHAR (MAX)   NULL,
    [InfotainmentSupplier]  NVARCHAR (MAX)   NULL,
    [ModifiedBy]            NVARCHAR (MAX)   NULL,
    [GarageRef]             NVARCHAR (MAX)   NULL,
    [ContractorRef]         NVARCHAR (MAX)   NULL,
    [LatestMOT]             DATETIME2 (7)    NULL,
    [NumberOfPitchesMOT]    INT              NOT NULL,
    [NumberOfSeatsMOT]      INT              NOT NULL,
    [RefrigerantQuantity]   INT              NOT NULL,
    [NumberOfCardReaders]   INT              NOT NULL,
    [Status]                NVARCHAR (50)    NULL,
    [SubContractorRef]      NVARCHAR (100)   NULL,
    [ContractRef]           NVARCHAR (200)   NULL,
    [CountingEquipment]     NVARCHAR (250)   NULL,
    [RefrigerantType]       NVARCHAR (MAX)   NULL
);


GO

