CREATE TABLE [stg].[RT_Journey] (
    [JourneyRef]                             CHAR (18)       NOT NULL,
    [SourceSystemCode]                       NVARCHAR (20)   NOT NULL,
    [SourceSystemEntryRef]                   BIGINT          NOT NULL,
    [OperatingDayDate]                       DATE            NOT NULL,
    [OperatingDayType]                       TINYINT         NULL,
    [LineNumber]                             NUMERIC (4)     NOT NULL,
    [LineDesignation]                        VARCHAR (8)     NOT NULL,
    [JourneyNumber]                          DECIMAL (6)     NOT NULL,
    [JourneyPatternId]                       NUMERIC (16)    NOT NULL,
    [TimedJourneyPatternId]                  BIGINT          NULL,
    [TransportModeCode]                      NVARCHAR (20)   NULL,
    [ContractCode]                           NVARCHAR (20)   NULL,
    [ContractorCode]                         NVARCHAR (20)   NULL,
    [ContractorGarageCode]                   NVARCHAR (20)   NULL,
    [PlannedStartDateTime]                   DATETIME2 (0)   NOT NULL,
    [PlannedEndDateTime]                     DATETIME2 (0)   NOT NULL,
    [PlannedStopCount]                       SMALLINT        NULL,
    [PlannedPaidDurationSeconds]             INT             NOT NULL,
    [PlannedPaidDistanceMeters]              DECIMAL (12, 2) NULL,
    [DatedVehicleJourneyId]                  NUMERIC (16)    NOT NULL,
    [DatedVehicleJourneyGid]                 NUMERIC (16)    NOT NULL,
    [IsExpectedByHistory]                    BIT             NULL,
    [IsReplaced]                             BIT             NOT NULL,
    [HasCancellation]                        BIT             NULL,
    [HasInconsistentObservation]             BIT             NULL,
    [ObservedStartDateTime]                  DATETIME2 (3)   NULL,
    [ObservedEndDateTime]                    DATETIME2 (3)   NULL,
    [VehicleSourceSystemCode]                NVARCHAR (20)   NULL,
    [PrimaryVehicleGid]                      NUMERIC (16)    NULL,
    [PrimaryVehicleNumber]                   NUMERIC (5)     NULL,
    [PrimaryVehicleAssignedFromDateTime]     DATETIME2 (3)   NULL,
    [PrimaryVehicleAssignedToDateTime]       DATETIME2 (3)   NULL,
    [PrimaryVehicleSeconds]                  INT             NULL,
    [TotalVehicleCount]                      TINYINT         NULL,
    [TotalVehicleSeconds]                    INT             NULL,
    [ObservedDepartureCount]                 SMALLINT        NULL,
    [EstimatedDepartureCount]                SMALLINT        NULL,
    [PrimaryShiftNumber]                     INT             NULL,
    [PrimaryStaffNumber]                     INT             NULL,
    [PrimaryDeviceId]                        INT             NULL,
    [TotalCheckInCount]                      SMALLINT        NULL,
    [TotalCheckOutCount]                     SMALLINT        NULL,
    [TotalCashTicketCount]                   SMALLINT        NULL,
    [TotalCashTicketAmount]                  INT             NULL,
    [TrackingSourceSystemCode]               NVARCHAR (20)   NULL,
    [PrimaryTrackingFaultyReportCount]       INT             NULL,
    [PrimaryTrackingTotalReportCount]        INT             NULL,
    [PrimaryTrackingObservedCoverageSeconds] INT             NULL,
    [PrimaryTrackingObservedCoverage]        FLOAT (53)      NULL,
    [PrimaryVehicleAssignmentType]           TINYINT         NULL,
    [OutlierClassification]                  TINYINT         NULL,
    [ExpectedDepartureCount]                 TINYINT         NULL,
    [ExpectedArrivalCount]                   TINYINT         NULL,
    [ObservedArrivalCount]                   TINYINT         NULL,
    [LineDirectionCode]                      NCHAR (1)       NULL
);


GO

