CREATE TABLE [stg].[RK_EquipmentExtract] (
    [EquipmentType]                    NVARCHAR (500)  NULL,
    [Owner]                            NVARCHAR (50)   NULL,
    [Operator]                         NVARCHAR (50)   NULL,
    [Contractor]                       NVARCHAR (50)   NULL,
    [Site]                             NVARCHAR (50)   NULL,
    [BusNo]                            NVARCHAR (50)   NULL,
    [Name]                             NVARCHAR (50)   NULL,
    [LabelName]                        NVARCHAR (50)   NULL,
    [ContainerDate]                    DATE            NULL,
    [SequenceNumber]                   INT             NULL,
    [Checksum]                         BINARY (32)     NULL,
    [SubMode]                          NVARCHAR (50)   NULL,
    [Connection]                       NVARCHAR (50)   NULL,
    [Operational]                      NVARCHAR (50)   NULL,
    [Mode]                             NVARCHAR (50)   NULL,
    [FareMode]                         NVARCHAR (50)   NULL,
    [ReceiptPrinterStatus]             NVARCHAR (50)   NULL,
    [ReceiptPrinterPaper]              NVARCHAR (50)   NULL,
    [ReceiptPrinterJam]                NVARCHAR (50)   NULL,
    [CSCStockStatus]                   NVARCHAR (50)   NULL,
    [CSCStockLevel]                    NVARCHAR (50)   NULL,
    [CSCStockJam]                      NVARCHAR (50)   NULL,
    [CSCStockBinLevel]                 NVARCHAR (50)   NULL,
    [CSCStockRemaining]                NVARCHAR (50)   NULL,
    [CSCStockRejected]                 NVARCHAR (50)   NULL,
    [CSCModuleConnection]              NVARCHAR (50)   NULL,
    [CSCModuleRW]                      NVARCHAR (50)   NULL,
    [CSCModuleAuthentication]          NVARCHAR (50)   NULL,
    [CSCDispenserConnection]           NVARCHAR (50)   NULL,
    [CSCDispenserRW]                   NVARCHAR (50)   NULL,
    [PowerPrimary]                     NVARCHAR (50)   NULL,
    [PowerBattery]                     NVARCHAR (50)   NULL,
    [EFTInternalStatus]                NVARCHAR (50)   NULL,
    [EFTBankServerComm]                NVARCHAR (50)   NULL,
    [EFTBankTransFile]                 NVARCHAR (50)   NULL,
    [EFTCardForgotten]                 NVARCHAR (50)   NULL,
    [EFTNotReEnable]                   NVARCHAR (50)   NULL,
    [EFTSecureZonePairing]             NVARCHAR (50)   NULL,
    [SecModSamStatus]                  NVARCHAR (50)   NULL,
    [SecModCSCComMKeys]                NVARCHAR (50)   NULL,
    [SecModTicketingKeys]              NVARCHAR (50)   NULL,
    [EODParameterStatus]               NVARCHAR (50)   NULL,
    [EODParameterActivation]           NVARCHAR (50)   NULL,
    [MiscDoor]                         NVARCHAR (50)   NULL,
    [MiscIntrusion]                    NVARCHAR (50)   NULL,
    [MiscAgentLogon]                   NVARCHAR (50)   NULL,
    [MiscTemperature]                  NVARCHAR (50)   NULL,
    [MiscTimeDiscrepancy]              NVARCHAR (50)   NULL,
    [MiscMemory]                       NVARCHAR (50)   NULL,
    [MiscRealTimeClock]                NVARCHAR (50)   NULL,
    [MiscGPSStatus]                    NVARCHAR (50)   NULL,
    [MiscGPSMode]                      NVARCHAR (50)   NULL,
    [MiscFlashStatus]                  NVARCHAR (50)   NULL,
    [MiscFlashCapacity]                NVARCHAR (50)   NULL,
    [MiscConsistency]                  NVARCHAR (50)   NULL,
    [SAMID]                            NVARCHAR (50)   NULL,
    [LogicalID]                        NVARCHAR (50)   NULL,
    [CreationDate]                     NVARCHAR (100)  NULL,
    [IPAddress]                        NVARCHAR (50)   NULL,
    [Location]                         NVARCHAR (50)   NULL,
    [LogicalPosition]                  INT             NULL,
    [ValidatorType]                    NVARCHAR (50)   NULL,
    [NOVASN]                           NVARCHAR (50)   NULL,
    [Comment]                          NVARCHAR (1000) NULL,
    [SoftwareProgramStatus]            NVARCHAR (200)  NULL,
    [SoftwareEODSystemParameter]       NVARCHAR (100)  NULL,
    [BackOfficeSystemParameter]        INT             NULL,
    [SoftwareEODEquipmentParameter]    NVARCHAR (100)  NULL,
    [BackOfficeEquipmentParameter]     INT             NULL,
    [SoftwareEODDictionary]            NVARCHAR (50)   NULL,
    [BackOfficeDictionary]             NVARCHAR (50)   NULL,
    [SoftwareEODEquipmentSoftware]     INT             NULL,
    [BackOfficeEquipmentSoftware]      INT             NULL,
    [SoftwareEODTime]                  INT             NULL,
    [BackOfficeTime]                   INT             NULL,
    [SoftwareEODTopology]              NVARCHAR (200)  NULL,
    [BackOfficeTopology]               NVARCHAR (100)  NULL,
    [SoftwareEODFare]                  NVARCHAR (50)   NULL,
    [BackOfficeFare]                   INT             NULL,
    [SoftwareEODPrimaryBlacklist]      INT             NULL,
    [BackOfficePrimaryBlacklist]       INT             NULL,
    [SoftwareEODSecondaryBlacklist]    INT             NULL,
    [BackOfficeSecondaryBlacklist]     INT             NULL,
    [SoftwareEODAgentlist]             INT             NULL,
    [BackOfficeAgentlist]              INT             NULL,
    [SoftwareEODActionList]            INT             NULL,
    [BackOfficeActionList]             INT             NULL,
    [SoftwareMainSoftware]             INT             NULL,
    [SoftwareHMISoftware]              INT             NULL,
    [SoftwareTP]                       INT             NULL,
    [SoftwareMAL]                      INT             NULL,
    [SoftwareUtilitiesPackage]         INT             NULL,
    [SoftwareOSKernel]                 INT             NULL,
    [SoftwareCSC1Firmware]             INT             NULL,
    [SoftwareCSC1TickKey]              INT             NULL,
    [SoftwareCSC2Firmware]             NVARCHAR (50)   NULL,
    [SoftwareCSC2TickKey]              NVARCHAR (50)   NULL,
    [SoftwareEFTFirmware]              NVARCHAR (50)   NULL,
    [SoftwareEFTPinpad]                NVARCHAR (50)   NULL,
    [SoftwareEFTRdrFirmware]           NVARCHAR (50)   NULL,
    [SoftwareEFTNI7Firmware]           NVARCHAR (50)   NULL,
    [SoftwareEFTPSAMFirmware]          NVARCHAR (50)   NULL,
    [EquipmentSupervised]              NVARCHAR (50)   NULL,
    [LatestEvent]                      NVARCHAR (50)   NULL,
    [AssociationDate]                  NVARCHAR (50)   NULL,
    [Collection]                       NVARCHAR (50)   NULL,
    [ShortName]                        NVARCHAR (50)   NULL,
    [FareReferencePoint]               NVARCHAR (50)   NULL,
    [StopReferencePoint]               NVARCHAR (50)   NULL,
    [DepotName]                        NVARCHAR (50)   NULL,
    [DepotNumber]                      NVARCHAR (200)  NULL,
    [SoftwareEODSystemParameterNew]    INT             NULL,
    [SoftwareEODEquipmentParameterNew] INT             NULL,
    [SoftwareEODDictionaryNew]         INT             NULL,
    [SoftwareEODEquipmentSoftwareNew]  INT             NULL,
    [SoftwareEODTimeNew]               INT             NULL,
    [SoftwareEODTopologyNew]           INT             NULL,
    [SoftwareEODFareNew]               INT             NULL,
    [SoftwareEODPrimaryBlacklistNew]   INT             NULL,
    [SoftwareEODSecondaryBlacklistNew] INT             NULL,
    [SoftwareEODAgentlistNew]          INT             NULL,
    [SoftwareEODActionListNew]         INT             NULL,
    [DeviceID]                         INT             CONSTRAINT [RK_EquipmentExtract_DeviceID] DEFAULT ((0)) NOT NULL,
    [LastModifiedEvent]                NVARCHAR (50)   NULL,
    [LastFileReceptionDate]            DATETIME        NULL
);


GO

