CREATE TABLE [stg_dim].[JourneyPattern] (
    [IsCurrent]                           BIT            NULL,
    [SourceSystemCode]                    NVARCHAR (20)  NOT NULL,
    [SourceSystemEntryId]                 BIGINT         NULL,
    [LineDirectionSourceSystemEntryId]    BIGINT         NULL,
    [JourneyPatternId]                    BIGINT         NULL,
    [JourneyPatternName]                  NVARCHAR (250) NULL,
    [JourneyPatternDisplayName]           NVARCHAR (250) NULL,
    [JourneyPatternPointCount]            INT            NULL,
    [JourneyPatternStopPointCount]        INT            NULL,
    [JourneyPatternGroupByKey]            NVARCHAR (250) NULL,
    [ValidFromDate]                       DATE           NULL,
    [ValidToDate]                         DATE           NULL,
    [JourneyPatternStartStopPointNumber]  INT            NULL,
    [JourneyPatternStartStopPointName]    NVARCHAR (250) NULL,
    [JourneyPatternEndStopPointNumber]    INT            NULL,
    [JourneyPatternEndStopPointName]      NVARCHAR (250) NULL,
    [JourneyPatternGroupByKeyAlternative] NVARCHAR (250) NULL,
    [JourneyPatternKey]                   INT            NULL,
    [LineKey]                             INT            NULL,
    [LineDirectionKey]                    INT            NULL,
    [JourneyPatternGroupKey]              INT            NULL,
    [JourneyPatternGroupCode]             NVARCHAR (20)  NULL,
    [JourneyPatternGroupName]             NVARCHAR (250) NULL,
    [JourneyPatternGroupDisplayName]      NVARCHAR (250) NULL,
    [RateAreaCombinationKey]              INT            NULL,
    [ProductGroupKey]                     INT            NULL,
    [ValidFromDateKey]                    INT            NULL,
    [ValidToDateKey]                      INT            NULL,
    [RateAreaCombinationCode]             NVARCHAR (20)  NULL,
    [RateAreaCombinationDisplayIndex]     INT            NULL,
    [RateAreaCombinationDisplayName]      NVARCHAR (250) NULL,
    [ProductGroupCode]                    NVARCHAR (20)  NULL,
    [ProductGroupDisplayIndex]            INT            NULL,
    [ProductGroupDisplayName]             NVARCHAR (250) NULL,
    [LineGid]                             NUMERIC (16)   NULL,
    [LineNumber]                          INT            NULL,
    [LineDesignation]                     NVARCHAR (8)   NULL,
    [LineName]                            NVARCHAR (250) NULL,
    [LineDisplayIndex]                    INT            NULL,
    [LineDisplayName]                     NVARCHAR (250) NULL,
    [LineDirectionGid]                    NUMERIC (16)   NULL,
    [LineDirectionCode]                   NVARCHAR (20)  NULL,
    [LineDirectionName]                   NVARCHAR (250) NULL,
    [LineDirectionDisplayIndex]           INT            NULL,
    [LineDirectionDisplayName]            NVARCHAR (250) NULL,
    [JourneyPatternDisplayIndex]          INT            NULL,
    [ProductGroupName]                    NVARCHAR (250) NULL,
    [DefaultTransportModeKey]             INT            NULL,
    [DefaultTransportModeCode]            NVARCHAR (20)  NULL,
    [DefaultTransportModeName]            NVARCHAR (250) NULL,
    [DefaultTransportModeDisplayIndex]    INT            NULL,
    [DefaultTransportModeDisplayName]     NVARCHAR (250) NULL
);


GO

