CREATE TABLE [stg_dim].[JourneyPatternPoint] (
    [JourneyPatternPointKey]                  INT               NULL,
    [MunicipalityKey]                         INT               NULL,
    [RateAreaKey]                             INT               NULL,
    [TariffZoneKey]                           INT               NULL,
    [ValidFromDateKey]                        INT               NULL,
    [ValidToDateKey]                          INT               NULL,
    [IsCurrent]                               BIT               NULL,
    [SourceSystemCode]                        NVARCHAR (20)     NULL,
    [SourceSystemEntryRef]                    NVARCHAR (30)     NULL,
    [MunicipalityDisplayIndex]                INT               NULL,
    [MunicipalityDisplayName]                 NVARCHAR (250)    NULL,
    [MunicipalityCode]                        NVARCHAR (20)     NULL,
    [RateAreaDisplayIndex]                    INT               NULL,
    [RateAreaDisplayName]                     NVARCHAR (250)    NULL,
    [RateAreaCode]                            NVARCHAR (20)     NULL,
    [TariffZoneDisplayIndex]                  INT               NULL,
    [TariffZoneDisplayName]                   NVARCHAR (250)    NULL,
    [TariffZoneNumber]                        INT               NULL,
    [JourneyPatternPointGid]                  BIGINT            NULL,
    [JourneyPatternPointNumber]               INT               NULL,
    [JourneyPatternPointRoadElementName]      NVARCHAR (250)    NULL,
    [JourneyPatternPointCoordinateSystemCode] NVARCHAR (20)     NULL,
    [JourneyPatternPointEastingCoordinate]    DECIMAL (18, 4)   NULL,
    [JourneyPatternPointNorthingCoordinate]   DECIMAL (18, 4)   NULL,
    [JourneyPatternPointLatitude]             DECIMAL (18, 12)  NULL,
    [JourneyPatternPointLongitude]            DECIMAL (18, 12)  NULL,
    [JourneyPatternPointGeography]            [sys].[geography] NULL,
    [JourneyPatternPointIsStopPoint]          BIT               NULL,
    [StopPointGid]                            BIGINT            NULL,
    [StopPointId]                             BIGINT            NULL,
    [StopPointOwner]                          INT               NULL,
    [StopPointNumber]                         INT               NULL,
    [StopPointTypeCode]                       NVARCHAR (20)     NULL,
    [StopPointDisplayIndex]                   INT               NULL,
    [StopPointDisplayName]                    NVARCHAR (250)    NULL,
    [StopPointName]                           NVARCHAR (250)    NULL,
    [StopPointShortName]                      NVARCHAR (250)    NULL,
    [StopPointIsForBoarding]                  BIT               NULL,
    [StopPointIsForAlighting]                 BIT               NULL,
    [StopAreaGid]                             BIGINT            NULL,
    [StopAreaOwner]                           INT               NULL,
    [StopAreaNumber]                          INT               NULL,
    [StopAreaTypeCode]                        NVARCHAR (20)     NULL,
    [StopAreaName]                            NVARCHAR (250)    NULL,
    [StopAreaShortName]                       NVARCHAR (250)    NULL,
    [StopAreaDisplayIndex]                    INT               NULL,
    [StopAreaDisplayName]                     NVARCHAR (250)    NULL,
    [StopAreaAbbreviation]                    NVARCHAR (10)     NULL,
    [StopAreaCoordinateSystemCode]            NVARCHAR (20)     NULL,
    [StopAreaCentroidEastingCoordinate]       DECIMAL (18, 4)   NULL,
    [StopAreaCentroidNorthingCoordinate]      DECIMAL (18, 4)   NULL,
    [StopAreaCentroidLatitude]                DECIMAL (18, 12)  NULL,
    [StopAreaCentroidLongitude]               DECIMAL (18, 12)  NULL,
    [StopAreaCentroidGeography]               [sys].[geography] NULL,
    [ValidFromDate]                           DATE              NULL,
    [ValidToDate]                             DATE              NULL,
    [LastModifiedUtcDateTime]                 DATETIME          NULL,
    CONSTRAINT [IX_JourneyPatternPoint_SourceSystemCode_SourceSystemEntryId_ValidFromDate] UNIQUE CLUSTERED ([SourceSystemCode] ASC, [SourceSystemEntryRef] ASC, [ValidFromDate] ASC)
);


GO

