CREATE TABLE [stg_dim].[JourneyPatternSection] (
    [JourneyPatternSectionKey]                          INT            NULL,
    [ValidFromDateKey]                                  INT            NULL,
    [ValidToDateKey]                                    INT            NULL,
    [IsCurrent]                                         BIT            NULL,
    [SourceSystemCode]                                  NVARCHAR (20)  NULL,
    [SourceSystemEntryId]                               BIGINT         NULL,
    [JourneyPatternId]                                  BIGINT         NULL,
    [SequenceNumber]                                    SMALLINT       NULL,
    [TimingPointSectionDisplayIndex]                    INT            NULL,
    [TimingPointSectionDisplayName]                     NVARCHAR (250) NULL,
    [StopPointSectionDisplayIndex]                      INT            NULL,
    [StopPointSectionDisplayName]                       NVARCHAR (250) NULL,
    [ValidFromDate]                                     DATE           NULL,
    [ValidToDate]                                       DATE           NULL,
    [TimingPointSectionMunicipalityKey]                 INT            NULL,
    [StopPointSectionDepartingMunicipalityKey]          INT            NULL,
    [TimingPointSectionMunicipalityDisplayIndex]        INT            NULL,
    [TimingPointSectionMunicipalityDisplayName]         NVARCHAR (250) NULL,
    [StopPointSectionArrivingMunicipalityKey]           INT            NULL,
    [StopPointSectionDepartingMunicipalityName]         NVARCHAR (250) NULL,
    [LineDirectionTopologicalOrder]                     SMALLINT       NULL,
    [LineDirectionLegacyOrder]                          INT            NULL,
    [JourneyPatternGroupCode]                           NVARCHAR (20)  NULL,
    [JourneyPatternGroupTopologicalOrder]               SMALLINT       NULL,
    [StopPointSectionFromGid]                           NUMERIC (16)   NULL,
    [StopPointSectionFromOwner]                         INT            NULL,
    [StopPointSectionFromNumber]                        INT            NULL,
    [StopPointSectionToGid]                             NUMERIC (16)   NULL,
    [StopPointSectionToOwner]                           INT            NULL,
    [StopPointSectionToNumber]                          INT            NULL,
    [TimingPointSectionFromStopPointId]                 INT            NULL,
    [StopPointSectionFromName]                          NVARCHAR (250) NULL,
    [StopPointSectionFromDisplayName]                   NVARCHAR (250) NULL,
    [StopPointSectionToName]                            NVARCHAR (250) NULL,
    [StopPointSectionToDisplayName]                     NVARCHAR (250) NULL,
    [StopPointSectionDepartingMunicipalityCode]         NVARCHAR (20)  NULL,
    [StopPointSectionDepartingMunicipalityDisplayIndex] INT            NULL,
    [StopPointSectionDepartingMunicipalityDisplayName]  NVARCHAR (250) NULL,
    [StopPointSectionArrivingMunicipalityCode]          NVARCHAR (20)  NULL,
    [StopPointSectionArrivingMunicipalityName]          NVARCHAR (250) NULL,
    [StopPointSectionArrivingMunicipalityDisplayIndex]  INT            NULL,
    [StopPointSectionArrivingMunicipalityDisplayName]   NVARCHAR (250) NULL,
    [TimingPointSectionFromAbbreviation]                NVARCHAR (20)  NULL,
    [TimingPointSectionToStopPointId]                   INT            NULL,
    [TimingPointSectionToAbbreviation]                  NVARCHAR (20)  NULL,
    [TimingPointSectionAbbreviation]                    NVARCHAR (250) NULL,
    [StopPointSectionAbbreviation]                      NVARCHAR (250) NULL,
    [StopPointSectionLinkRef]                           VARCHAR (20)   NULL,
    [StopPointSectionFromStopPointId]                   INT            NULL,
    [StopPointSectionFromAbbreviation]                  NVARCHAR (20)  NULL,
    [StopPointSectionToStopPointId]                     INT            NULL,
    [StopPointSectionToAbbreviation]                    NVARCHAR (20)  NULL,
    CONSTRAINT [BK_JourneyPatternSection] UNIQUE CLUSTERED ([JourneyPatternId] ASC, [SequenceNumber] ASC)
);


GO

