CREATE TABLE [stg_dim].[StopPoint] (
    [StopPointKey]                            INT               NULL,
    [MunicipalityKey]                         INT               NULL,
    [RateAreaKey]                             INT               NULL,
    [TariffZoneKey]                           INT               NULL,
    [ValidFromDateKey]                        INT               NULL,
    [ValidToDateKey]                          INT               NULL,
    [IsCurrent]                               BIT               NULL,
    [SourceSystemCode]                        NVARCHAR (20)     NULL,
    [SourceSystemEntryId]                     NVARCHAR (30)     NULL,
    [MunicipalityDisplayIndex]                INT               NULL,
    [MunicipalityDisplayName]                 NVARCHAR (250)    NULL,
    [MunicipalityCode]                        NVARCHAR (20)     NULL,
    [RateAreaDisplayIndex]                    INT               NULL,
    [RateAreaDisplayName]                     NVARCHAR (250)    NULL,
    [RateAreaCode]                            NVARCHAR (20)     NULL,
    [TariffZoneDisplayIndex]                  INT               NULL,
    [TariffZoneDisplayName]                   NVARCHAR (250)    NULL,
    [TariffZoneNumber]                        INT               NULL,
    [JourneyPatternPointGid]                  BIGINT            NULL,
    [JourneyPatternPointNumber]               INT               NULL,
    [JourneyPatternPointRoadElementName]      NVARCHAR (250)    NULL,
    [JourneyPatternPointCoordinateSystemCode] NVARCHAR (20)     NULL,
    [JourneyPatternPointEastingCoordinate]    DECIMAL (18, 4)   NULL,
    [JourneyPatternPointNorthingCoordinate]   DECIMAL (18, 4)   NULL,
    [StopPointGid]                            BIGINT            NULL,
    [StopPointNumber]                         INT               NULL,
    [StopPointTypeCode]                       NVARCHAR (20)     NULL,
    [StopPointDisplayIndex]                   INT               NULL,
    [StopPointDisplayName]                    NVARCHAR (250)    NULL,
    [StopPointName]                           NVARCHAR (250)    NULL,
    [StopPointShortName]                      NVARCHAR (250)    NULL,
    [StopPointIsForBoarding]                  BIT               NULL,
    [StopPointIsForAlighting]                 BIT               NULL,
    [ValidFromDate]                           DATE              NULL,
    [ValidToDate]                             DATE              NULL,
    [LastModifiedUtcDateTime]                 DATETIME          NULL,
    [JourneyPatternPointLatitude]             DECIMAL (18, 12)  NULL,
    [JourneyPatternPointLongitude]            DECIMAL (18, 12)  NULL,
    [JourneyPatternPointGeography]            [sys].[geography] NULL,
    [StopPointOwner]                          INT               NULL,
    [StopPointId]                             BIGINT            NULL,
    CONSTRAINT [IX_StopPoint_SourceSystemCode_SourceSystemEntryId_ValidFromDate] UNIQUE CLUSTERED ([SourceSystemCode] ASC, [SourceSystemEntryId] ASC, [ValidFromDate] ASC)
);


GO

