CREATE TABLE [fact].[ACCT_Settlement_Interval_Daily] (
    [SourceSystemCode]             NVARCHAR (20) NOT NULL,
    [SourceSystemEntryRef]         NVARCHAR (50) NOT NULL,
    [JourneyRef]                   CHAR (18)     NOT NULL,
    [OperatingDateKey]             INT           NULL,
    [ContractorKey]                INT           NULL,
    [ContractorCode]               NVARCHAR (50) NULL,
    [ContractKey]                  INT           NULL,
    [ContractCode]                 NVARCHAR (50) NULL,
    [ContractorGarageKey]          INT           NULL,
    [ContractorGarageCode]         NVARCHAR (50) NULL,
    [ClassKey]                     INT           NULL,
    [Class]                        NVARCHAR (2)  NULL,
    [FromJourneyPointRef]          NVARCHAR (22) NOT NULL,
    [ToJourneyPointRef]            NVARCHAR (22) NOT NULL,
    [FromStopPointKey]             INT           NULL,
    [ToStopPointKey]               INT           NULL,
    [FromStopPointNumber]          INT           NULL,
    [ToStopPointNumber]            INT           NULL,
    [Type]                         NVARCHAR (50) NULL,
    [SettlementKey]                INT           NULL,
    [SettlementCode]               INT           NULL,
    [PlannedDuration]              FLOAT (53)    NULL,
    [PartialDuration]              FLOAT (53)    NULL,
    [IsException]                  INT           NULL,
    [PaymentTypeKey]               INT           NULL,
    [PaymentType]                  NVARCHAR (20) NULL,
    [VehicleKey]                   INT           NULL,
    [VehicleNumber]                INT           NULL,
    [LineKey]                      INT           NULL,
    [LineNumber]                   INT           NULL,
    [LineDesignation]              NVARCHAR (20) NULL,
    [LineDirectionCode]            INT           NULL,
    [Hash]                         BINARY (32)   NULL,
    [Inserted]                     DATETIME2 (7) NULL,
    [Updated]                      DATETIME2 (7) NULL,
    [FirstPlannedSequenceNumber]   INT           NULL,
    [LastPlannedSequenceNumber]    INT           NULL,
    [FirstPlannedDepartureDateKey] INT           NULL,
    [FirstPlannedDepartureTimeKey] INT           NULL,
    [JourneyNumber]                INT           NULL,
    [PlannedStopCount]             INT           NULL,
    [IsMultipleIntervals]          INT           NULL,
    [IsRPSMatch]                   INT           NULL,
    CONSTRAINT [PK_ACCT_Settlement_Interval_Daily] PRIMARY KEY CLUSTERED ([JourneyRef] ASC, [FromJourneyPointRef] ASC, [ToJourneyPointRef] ASC)
);


GO

