CREATE TABLE [stg_fact].[ACCT_RevenueSharing_TicketSale] (
    [TicketSaleKey]            INT             NULL,
    [DateKey]                  INT             NULL,
    [OriginTariffZoneKey]      INT             NULL,
    [DestinationTariffZoneKey] INT             NULL,
    [JourneyPatternPointKey]   INT             NULL,
    [TicketTypeKey]            INT             NULL,
    [SharingMethodKey]         INT             NULL,
    [FareSetKey]               INT             NULL,
    [SourceSystemCode]         NVARCHAR (20)   NULL,
    [SourceSystemEntryRef]     NVARCHAR (255)  NULL,
    [TicketTypeCode]           NVARCHAR (20)   NULL,
    [OriginTariffZoneRef]      NVARCHAR (20)   NULL,
    [OriginRateAreaCode]       NVARCHAR (20)   NULL,
    [DestinationTariffZoneRef] NVARCHAR (20)   NULL,
    [DestinationRateAreaCode]  NVARCHAR (20)   NULL,
    [SharingMethodCode]        NVARCHAR (20)   NULL,
    [FareSetCode]              NVARCHAR (20)   NULL,
    [ZoneCount]                INT             NULL,
    [AdultCount]               DECIMAL (18, 2) NULL,
    [ChildCount]               DECIMAL (18, 2) NULL,
    [PassengerCount]           DECIMAL (18, 2) NULL,
    [Amount]                   DECIMAL (18, 2) NULL,
    [PassengerTypeKey]         INT             NULL,
    [Date]                     DATE            NULL,
    [ValidityStartDate]        DATE            NULL,
    [ValidityEndDate]          DATE            NULL,
    [PaidZoneCount]            INT             NULL,
    [RevenueTypeKey]           INT             NULL,
    [SalesChannelKey]          INT             NULL,
    [MediaTypeKey]             INT             NULL,
    [RevenueTypeCode]          NVARCHAR (20)   NULL,
    [SalesChannelCode]         NVARCHAR (20)   NULL,
    [MediaTypeCode]            NVARCHAR (20)   NULL,
    [ValidityDays]             DECIMAL (18, 2) NULL,
    [PassengerTypeCode]        NVARCHAR (20)   NULL,
    [SourceSystemProductRef]   NVARCHAR (255)  NULL,
    [JourneyRef]               NVARCHAR (18)   NULL,
    [JourneyPointRef]          NVARCHAR (22)   NULL,
    [TimeKey]                  INT             NULL
);


GO

