CREATE TABLE [stg_fact].[ACCT_Settlement_Interval_Monthly] (
    [SourceSystemCode]              NVARCHAR (20) NOT NULL,
    [SourceSystemEntryRef]          NVARCHAR (50) NOT NULL,
    [JourneyRef]                    CHAR (18)     NULL,
    [OperatingDateKey]              INT           NULL,
    [ContractorKey]                 INT           NULL,
    [ContractorCode]                NVARCHAR (50) NULL,
    [ContractKey]                   INT           NULL,
    [ContractCode]                  NVARCHAR (50) NULL,
    [ContractorGarageKey]           INT           NULL,
    [ContractorGarageCode]          NVARCHAR (50) NULL,
    [ClassKey]                      INT           NULL,
    [Class]                         NVARCHAR (2)  NULL,
    [FromJourneyPointRef]           NVARCHAR (22) NULL,
    [ToJourneyPointRef]             NVARCHAR (22) NULL,
    [FromStopPointKey]              INT           NULL,
    [FromStopPointNumber]           INT           NULL,
    [ToStopPointNumber]             INT           NULL,
    [ToStopPointKey]                INT           NULL,
    [Type]                          NVARCHAR (50) NULL,
    [SettlementKey]                 INT           NULL,
    [SettlementCode]                INT           NULL,
    [PlannedDuration]               FLOAT (53)    NULL,
    [PartialDuration]               FLOAT (53)    NULL,
    [IsException]                   INT           NULL,
    [PaymentTypeKey]                INT           NULL,
    [PaymentType]                   NVARCHAR (20) NULL,
    [VehicleKey]                    INT           NULL,
    [VehicleNumber]                 INT           NULL,
    [LineKey]                       INT           NULL,
    [LineNumber]                    INT           NULL,
    [LineDesignation]               NVARCHAR (20) NULL,
    [LineDirectionCode]             INT           NULL,
    [FirstPlannedSequenceNumber]    INT           NULL,
    [LastPlannedSequenceNumber]     INT           NULL,
    [FirstPlannedDepartureDateTime] DATETIME2 (7) NULL,
    [LastPlannedArrivalDateTime]    DATETIME2 (7) NULL,
    [FirstPlannedDepartureDateKey]  INT           NULL,
    [FirstPlannedDepartureDate]     DATE          NULL,
    [FirstPlannedDepartureTimeKey]  INT           NULL,
    [FirstPlannedDepartureTime]     TIME (0)      NULL,
    [JourneyNumber]                 INT           NULL,
    [PlannedStopCount]              INT           NULL,
    [IsMultipleIntervals]           INT           NULL,
    [IsRPSMatch]                    INT           NULL
);


GO

