CREATE TABLE [stg_fact].[QA_ServiceQualitySurvey] (
    [Id]                        BIGINT          NOT NULL,
    [InterviewerId]             BIGINT          NULL,
    [RespondentId]              BIGINT          NOT NULL,
    [Time]                      DATETIME        NULL,
    [DateKey]                   INT             NULL,
    [VehicleRef]                INT             NOT NULL,
    [Age]                       INT             NULL,
    [Gender]                    NVARCHAR (20)   NULL,
    [DurationInMinutes]         INT             NULL,
    [Purpose]                   INT             NULL,
    [Frequency]                 INT             NULL,
    [Placement]                 INT             NULL,
    [Language]                  INT             NULL,
    [JourneyRef]                CHAR (18)       NULL,
    [FromStopPointId]           INT             NULL,
    [InterviewerStartStopId]    INT             NULL,
    [InterviewerEndStopId]      INT             NULL,
    [InterviewerStartStopKey]   INT             NOT NULL,
    [InterviewerEndStopKey]     INT             NOT NULL,
    [LineKey]                   INT             NOT NULL,
    [LineNumber]                INT             NULL,
    [LineDisplayName]           NVARCHAR (250)  NULL,
    [SurveyQuestionKey]         INT             NOT NULL,
    [SurveyAnswerKey]           INT             NOT NULL,
    [SurveyQuestionType]        BIGINT          NULL,
    [AnswerValue]               BIGINT          NOT NULL,
    [QuestionId]                BIGINT          NOT NULL,
    [Weight]                    DECIMAL (18, 4) NULL,
    [ContractCode]              NVARCHAR (20)   NULL,
    [ContractKey]               INT             NOT NULL,
    [ContractName]              NVARCHAR (250)  NULL,
    [ContractorCode]            NVARCHAR (20)   NULL,
    [ContractorKey]             INT             NOT NULL,
    [ContractorName]            NVARCHAR (250)  NULL,
    [GarageCode]                NVARCHAR (20)   NULL,
    [GarageKey]                 INT             NOT NULL,
    [Target]                    DECIMAL (9, 2)  NULL,
    [MinTarget]                 DECIMAL (9, 2)  NULL,
    [Importance]                DECIMAL (9, 2)  NULL,
    [NytBynetPoints]            DECIMAL (9, 2)  NULL,
    [NytBynet]                  INT             NULL,
    [NytBynetDataReplaceMethod] INT             NULL,
    [MaxBonus]                  DECIMAL (9, 2)  NULL,
    [MaxSetOff]                 DECIMAL (9, 2)  NULL,
    [LowBoundary]               INT             NULL,
    [HighBoundary]              INT             NULL,
    [MeasuringPeriod]           NVARCHAR (255)  NOT NULL,
    [ValidFromDate]             DATE            NOT NULL,
    [ValidToDate]               DATE            NOT NULL,
    [NonNytBynetPeriodStart]    DATE            NULL,
    [NonNytBynetPeriodEnd]      DATE            NULL,
    [NytBynetWeight]            INT             NULL,
    [IsZeroed]                  INT             NULL,
    [MeasuringPeriodKey]        INT             NULL
);


GO

