CREATE TABLE [stg_fact].[QA_ServiceQualitySurvey_Answer] (
    [DateKey]                  INT            NULL,
    [TimeKey]                  INT            NULL,
    [AgeKey]                   INT            NULL,
    [GenderKey]                INT            NULL,
    [DefaultTransportModeKey]  INT            CONSTRAINT [DF_QA_ServiceQualitySurvey_Answer_DefaultTransportModeKey] DEFAULT ((-1)) NULL,
    [LineKey]                  INT            NULL,
    [TimeSpanKey]              INT            NULL,
    [ContractorKey]            INT            NULL,
    [OperatingDayTypeKey]      INT            NULL,
    [PurposeKey]               VARCHAR (255)  NULL,
    [FrequencyKey]             VARCHAR (255)  NULL,
    [PlacementKey]             VARCHAR (255)  NULL,
    [LanguageKey]              VARCHAR (255)  NULL,
    [FromStopPointNumberKey]   INT            NULL,
    [SurveyQuestionKey]        INT            NULL,
    [SurveyAnswerKey]          INT            NULL,
    [InterviewTypeKey]         INT            NULL,
    [DataQualityTypeKey]       INT            NULL,
    [JourneyRef]               NCHAR (18)     NULL,
    [FileId]                   INT            NULL,
    [SourceSystemCode]         NVARCHAR (20)  NULL,
    [SourceSystemEntryId]      VARCHAR (255)  NULL,
    [InterviewId]              VARCHAR (255)  NULL,
    [InterviewerId]            VARCHAR (255)  NULL,
    [InterviewerStartStopNo]   INT            NULL,
    [InterviewerEndStopNo]     INT            NULL,
    [RespondentId]             VARCHAR (255)  NULL,
    [AnswerValue]              VARCHAR (255)  NULL,
    [InterviewStartLatitude]   DECIMAL (8, 6) CONSTRAINT [DF_QA_ServiceQualitySurvey_Answer_InterviewStartLatitude] DEFAULT ((-1)) NULL,
    [InterviewStartLongitude]  DECIMAL (8, 6) CONSTRAINT [DF_QA_ServiceQualitySurvey_Answer_InterviewStartLongitude] DEFAULT ((-1)) NULL,
    [DatedVehicleJourneyId]    DECIMAL (16)   NULL,
    [SourceSystemEntryRef]     NVARCHAR (100) NULL,
    [Line]                     VARCHAR (255)  NULL,
    [ContractorName]           VARCHAR (255)  NULL,
    [BusNo]                    VARCHAR (255)  NULL,
    [PurposeValue]             VARCHAR (255)  NULL,
    [TimeSpanTotalMinutes]     VARCHAR (255)  NULL,
    [FrequencyValue]           VARCHAR (255)  NULL,
    [GenderNumber]             VARCHAR (255)  NULL,
    [AgeYears]                 VARCHAR (255)  NULL,
    [PlacementValue]           VARCHAR (255)  NULL,
    [LanguageValue]            VARCHAR (255)  NULL,
    [FromStopPointNumber]      VARCHAR (255)  NULL,
    [DateTime]                 DATETIME       NULL,
    [ContractorCode]           NVARCHAR (20)  NULL,
    [DefaultTransportModeCode] NVARCHAR (20)  NULL,
    [LineNumber]               INT            NULL,
    [OperatingDayType]         INT            NULL
);


GO

