CREATE TABLE [stg_fact].[RT_DrivingReliability_TimingPoint] (
    [DrivingReliabilityTimingPointKey] INT           NULL,
    [DateKey]                          INT           NULL,
    [TimeKey]                          INT           NULL,
    [JourneyPlannedStartTimeKey]       INT           NULL,
    [OperatingDayTypeKey]              INT           NULL,
    [ContractorKey]                    INT           NULL,
    [ContractorGarageKey]              INT           NULL,
    [JourneyPatternKey]                INT           NULL,
    [JourneyPatternSectionKey]         INT           NULL,
    [StopPointKey]                     INT           NULL,
    [ReliabilityTypeKey]               INT           NULL,
    [SourceSystemCode]                 NVARCHAR (20) NULL,
    [SourceSystemEntryId]              NVARCHAR (22) NULL,
    [OperatingDayDate]                 DATE          NULL,
    [OperatingDayType]                 TINYINT       NULL,
    [ContractorCode]                   NVARCHAR (20) NULL,
    [ContractorGarageCode]             NVARCHAR (20) NULL,
    [LineNumber]                       INT           NULL,
    [LineDirectionCode]                NVARCHAR (20) NULL,
    [JourneyPatternId]                 BIGINT        NULL,
    [JourneyPlannedStartDateTime]      DATETIME2 (0) NULL,
    [StopPointOwner]                   INT           NULL,
    [StopPointNumber]                  INT           NULL,
    [PlannedDepartureDateTime]         DATETIME2 (0) NULL,
    [ObservedDepartureDateTime]        DATETIME2 (0) NULL,
    [SequenceNumber]                   SMALLINT      NULL,
    [Hour]                             TINYINT       NULL,
    [PlannedDeparturesPerHour]         TINYINT       NULL,
    [PlannedStopSeconds]               SMALLINT      NULL,
    [ObservedStopSeconds]              SMALLINT      NULL,
    [PlannedFrequencySeconds]          INT           NULL,
    [ObservedFrequencySeconds]         INT           NULL,
    [TimetableOffsetSeconds]           INT           NULL,
    [FrequencyOffsetSeconds]           INT           NULL,
    [ReliabilityType]                  TINYINT       NULL,
    [IsReliable]                       TINYINT       NULL,
    [ContractKey]                      INT           NULL,
    [OutlierClassificationKey]         INT           NULL,
    [ContractCode_old]                 NCHAR (10)    NULL,
    [PlannedArrivalDateTime]           DATETIME2 (0) NULL,
    [ObservedArrivalDateTime]          DATETIME2 (0) NULL,
    [IsFirstStopPoint]                 TINYINT       NULL,
    [IsLastStopPoint]                  TINYINT       NULL,
    [IsRingLine]                       TINYINT       NULL,
    [StrategicNetCode]                 NVARCHAR (20) NULL,
    [StrategicNetKey]                  INT           NULL,
    [IsBunching]                       TINYINT       NULL,
    [OutlierClassification]            TINYINT       NULL,
    [ContractCode]                     NVARCHAR (20) NULL
);


GO

