name: Deploy to Development and Test
on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Deploy_dev:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '5.0.x' 
    - name: Restore dependencies 
      working-directory: db-deploy
      run: dotnet restore      
    - name: Deploy to dev
      working-directory: db-deploy
      env: 
        ConnectionString: ${{ secrets.AZURE_SQL_CONNECTION_STRING_DEV }}        
      run: dotnet run
  Test:
    runs-on: ubuntu-latest
    needs: [Deploy_dev]
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '5.0.x' 
    - name: Restore dependencies 
      working-directory: db-test
      run: dotnet restore      
    - name: Run Tests
      working-directory: db-test
      env: 
        ConnectionString: ${{ secrets.AZURE_SQL_CONNECTION_STRING_DEV }}        
      run: dotnet test
  # Deploy_prd:
  #   runs-on: ubuntu-latest
  #   needs: [Test]
  #   steps:
  #   - name: Checkout Repo
  #     uses: actions/checkout@v4
  #   - name: Setup .NET Core
  #     uses: actions/setup-dotnet@v4
  #     with:
  #       dotnet-version: '5.0.x' 
  #   - name: Restore dependencies 
  #     working-directory: db-deploy
  #     run: dotnet restore      
  #   - name: Deploy to prd
  #     working-directory: db-deploy
  #     env: 
  #       ConnectionString: ${{ secrets.AZURE_SQL_CONNECTION_STRING_PRD }}        
  #     run: dotnet run
      
      
